### PR TITLE
Create arm-create-package.yml

### PR DESCRIPTION
**Pull request by anthonydahanne**
This PR updates the pipeline builder create-package workflow automation to support multi-arch builds of this buildpack (ARM64 and AMD64). **The ARM64 image should be considered experimental for now**, since the official [Paketo RFC](https://github.com/paketo-buildpacks/rfcs/pull/288) and [CNB RFCs](https://github.com/buildpacks/rfcs/pull/295) related to multi-arch have not been merged in yet.
It uses an **experimental version of the pack CLI** (https://github.com/buildpacks/pack/pull/2086), and is based off of the upstream CNB RFC that is currently IN PROGRESS. This workflow will definitely be subject to change when an official `pack` release comes out, and if there are any changes to the upstream RFC.
Once we have merged this and seen it work on `main`, we will contribute it into the upstream pipeline-builder repository.
(@sophiewigmore )

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by anthonydahanne** [comment]
this should be moved under pipeline builder, right @dmikusa ?

**Comment by dmikusa** [comment]
Yes, this is going to be a pipeline-builder change.

**Comment by dmikusa** [comment]
We've implemented some things in pipeline-builder, is this PR still needed?

**Comment by anthonydahanne** [comment]
@dmikusa well, we don't "need" it, it's more like a playground to test `arm64` package publication.

AFAIK, `pipeline-builder` does not support generating such a workflow,  so this workflow should go in pipeline-builder and be generated as `pb-create-package-arm64.yml` when a 

```
package:
  arm64: true
```
property is set.

Also, it won't be the end of it, we'll also need another `pb-merge-manifest.yml` that will push the dual arch buildpack

**Comment by dmikusa** [comment]
Gotcha, OK.

**Comment by sophiewigmore** [comment]
Per convo with Anthony - we'll prob need to update some stuff in the buildpack.toml around the `arch` field for the dependencies. We will need libpak changes to work with that too, most likely.

**Pull request closed without merging**
